### ISSUE TITLE
Review in progress

### ISSUE THREAD

**Issue by zahraoui-mohammed** [benbella19/codingtest#1]
Hello Mr @benbella19,

After reviewing your latest updates, here are some points that require your attention. It is essential to carefully address these items, as they directly impact the overall quality and functionality of the application:

- Return types and type hints are missing.
- Follow PSR 1-2 notations.
- User can upload image when creating the product 
- User can select category when creating the product
- Validation is missing when creating the product or the category

Please ensure that all the above issues are rectified. It is important to carefully follow the instructions and review the "Links and Resources" section to avoid missing any key components. Your attention to these details is critical to ensure the strength of your coding quality.

**Comment by benbella19** [comment]
done
